"""empty message

Revision ID: 00f3cdbb0b99
Revises: d8f3f1468703
Create Date: 2022-12-07 01:34:21.407389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f3cdbb0b99'
down_revision = 'd8f3f1468703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
